/SafetyMonitorNode:
  ros__parameters:
  
  # Still needs to be changed for more accurate paths
    left_image: "/left"
    right_image: "/right"
    depth_image: "/depth"
    left_info: "/left/info"
    right_info: "/right/info"
    depth_info: "/depth/info"
    cone_array_topic: "/cones"
    path_topic: "/path"
    control_topic: "/control"
    state_topic: "/state"
    acu_topic: "/pc_origin/mission"

    limg_freq: 100
	  rimg_freq: 100
	  dimg_freq: 100
	  linf_freq: 100
	  rinf_freq: 100
    dinf_freq: 100
	  mapr_freq: 200
	  plan_freq: 200
	  ctrl_freq: 200

    padding: 0.7