/SafetyMonitorNode:
  ros__parameters:

  topics: ["/mapping/cones","/ekf/state","/ekf/map","/planned_path_topic","/pc_origin/dynamics", "/acu_origin/dynamics"]

    freqs: [100.0,100.0,100.0,100.0,100.0,100.0]

    state_topic: "/pc_origin/system_status/critical_as/state"
    mission_topic: "/pc_origin/system_status/critical_as/mission"

    padding: 1.7