/SafetyMonitorNode:
  ros__parameters:

    topics: ["/zed/left/image_raw","/zed/image_raw","/zed/depth/image_raw","/zed/left/camera_info","/zed/right/camera_info","/zed/depth/camera_info","/mapping/cones","/planning/path","/control/command"]

    freqs: [100.0,100.0,100.0,100.0,100.0,100.0,200.0,200.0,200.0]

    state_topic: "/state"
    acu_topic: "/pc_origin/mission"

    padding: 1.7